# Generated by Django 6.1.1 on 2026-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carinventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
